// Code generated by 'yaegi extract autochrome/executor/chrome'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package symbols

import (
	"autochrome/executor/chrome"
	"reflect"
)

func init() {
	Symbols["autochrome/executor/chrome/chrome"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Delete": reflect.ValueOf(chrome.Delete),
		"New":    reflect.ValueOf(chrome.New),

		// type definitions
		"Chrome": reflect.ValueOf((*chrome.Chrome)(nil)),
	}
}
